kind = "web"
previewPath = "/"
title = "Mercado en Línea Culiacán"
version = "1.0.0"
id = "artifacts/mercado-culiacan"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 20389
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/mercado-culiacan run dev"

[services.env]
PORT = "20389"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/mercado-culiacan", "run", "build"]
publicDir = "artifacts/mercado-culiacan/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
